# Generated by Django 4.2.7 on 2024-08-20 06:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jobs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('register_number', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField(validators=[jobs.validators.validate_year])),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)])),
                ('board', models.CharField(choices=[('State Board', 'State'), ('CBSE', 'Cbse'), ('ICSE', 'Icse'), ('Matric', 'Matric')], max_length=30)),
                ('marksheet', models.FileField(blank=True, null=True, upload_to='HSC/')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default='TAN00000', max_length=50)),
                ('mark', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)])),
                ('position', models.CharField(choices=[('Cluster Programme Manager', 'Cluster Manager'), ('Clinical Services Officer', 'Clinical Officer'), ('Data Monitoring and Documentation Officer', 'Data Monitoring Officer'), ('Deputy Director (LS)', 'Deputy Ls Director'), ('Deputy Director (SI)', 'Deputy Si Director'), ('Assistant Director (BSD) /(ICTC)', 'Assistant Ictc Director'), ('Assistant Director (PREVENTION) /(TI)', 'Assistant Ti Director'), ('Assistant Director (IEC)', 'Assistant Iec Director')], max_length=100)),
                ('signature', models.FileField(blank=True, null=True, upload_to='signature/')),
                ('applied_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('hsc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailOfJob_hsc', to='jobs.hsc')),
            ],
        ),
        migrations.CreateModel(
            name='SSLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('register_number', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField(validators=[jobs.validators.validate_year])),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)])),
                ('board', models.CharField(choices=[('State Board', 'State'), ('CBSE', 'Cbse'), ('ICSE', 'Icse'), ('Matric', 'Matric')], max_length=30)),
                ('marksheet', models.FileField(blank=True, null=True, upload_to='SSLC/')),
            ],
        ),
        migrations.CreateModel(
            name='UG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('register_number', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField(validators=[jobs.validators.validate_year])),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)])),
                ('marksheet', models.FileField(blank=True, null=True, upload_to='UG/')),
            ],
        ),
        migrations.CreateModel(
            name='PreferedExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('NACO', 'Naco'), ('TANSACS', 'Tansacs'), ('TSU', 'Tsu')], max_length=100)),
                ('year', models.IntegerField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='PreferedExperience/')),
                ('NOC', models.FileField(blank=True, null=True, upload_to='NOC/')),
                ('job', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pexp', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('register_number', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField(validators=[jobs.validators.validate_year])),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)])),
                ('marksheet', models.FileField(blank=True, null=True, upload_to='PG/')),
                ('job', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg', to='jobs.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='sslc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailOfJob_sslc', to='jobs.sslc'),
        ),
        migrations.AddField(
            model_name='job',
            name='ug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailOfJob_ug', to='jobs.ug'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='Experience/')),
                ('course', models.CharField(choices=[('UG', 'Ug'), ('PG', 'Pg'), ('PHD', 'Phd')], default='UG', max_length=50)),
                ('job', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp', to='jobs.job')),
            ],
        ),
    ]
