# Generated by Django 4.2.7 on 2024-08-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='degree',
            field=models.TextField(blank=True, null=True),
        ),
    ]
