# Generated by Django 4.2.7 on 2024-09-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='joined_date',
            field=models.DateField(default='2024-09-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='upto_date',
            field=models.DateField(default='2024-09-24'),
            preserve_default=False,
        ),
    ]
