# Generated by Django 4.2.7 on 2024-09-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_experience_currently_working_experience_joined_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='year',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True),
        ),
    ]
