# Generated by Django 4.2.7 on 2024-09-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_experience_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='upto_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
