# Generated by Django 4.2.7 on 2024-09-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_experience_upto_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='year',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=19, null=True),
        ),
    ]
