# Generated by Django 4.2.7 on 2024-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_experience_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='year_month',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
