# Generated by Django 4.2.7 on 2024-08-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instruction_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
